name: Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@main
        with:
          node_version: '14.x'
          
      - name: Install dependencies
        run: yarn
      
      - name: run linting
        run: yarn lint